name: "Variables Demo"

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

parameters:
- name : Region
  displayName: Which region to deploy to.
  type: string
  default: 'West Europe'
  values:
  - 'Germany West Central'
  - 'West Europe'
- name : Environment
  displayName: Environment to deploy.
  type: string
  default: Dev
  values:
  - Dev
  - QA
  - PRD

#- group: GlobalVariables
variables:
#- template: vars.yml  # Template reference  
  DeploymentDefaultLocation: 'westeurope'
  AZRMServiceConnectionName: 'ARMConnection'
  lowerEnvironment: ${{ lower(parameters.Environment) }}

stages:
- stage: Stage1
  displayName: "Stage 1"
  jobs:
  - job: Write_Output_Variables
    strategy:
      maxParallel: 2
    steps:
    - script: |
        echo Buildnumber $(Build.BuildNumber)
        echo VMAdminPWD $(VMAdminPWD)
        echo AzSubscriptionID $(AzSubscriptionID)
        echo ServiceConnectionName $(ServiceConnectionName)
      displayName: 'echo Build Number'
    - powershell: |
        # Using an input-macro:
        Write-Host "This works: $(VMAdminPWD)"

        # Using the env var directly:
        Write-Host "This does not work: $env:VMAdminPWD"

        # Using the mapped env var:
        Write-Host "This works: $env:MY_MAPPED_ENV_VAR"    # Recommended
      env:
        MY_MAPPED_ENV_VAR: $(VMAdminPWD)