name: "Variables Demo"

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

parameters:
- name : Region
  displayName: Which region to deploy to.
  type: string
  default: 'West Europe'
  values:
  - 'Germany West Central'
  - 'West Europe'
- name : Environment
  displayName: Environment to deploy.
  type: string
  default: Dev
  values:
  - Dev
  - QA
  - PRD

#- group: GlobalVariables
variables:
  DeploymentDefaultLocation: 'westeurope'
  AZRMServiceConnectionName: 'ARMConnection'
  lowerEnvironment: ${{ lower(parameters.Environment) }}
  ServiceConnectionName: 'ARMConnection'

stages:
- stage: Stage1
  displayName: "Stage 1"
  jobs:
  - job:
    steps:
    - script: |
        echo Buildnumber $(Build.BuildNumber)
      displayName: 'echo Build Number'
    - script: |
        echo VMAdminPWD should be hidden:
        echo VMAdminPWD $(VMAdminPWD)
        echo VMAdminPWD ${{ VMAdminPWD }}
        echo AzSubscriptionID should be visible:
        echo AzSubscriptionID $(AzSubscriptionID)
        echo AzSubscriptionID ${{ AzSubscriptionID }}
        echo ServiceConnectionName Should be visible:
        echo ServiceConnectionName $(ServiceConnectionName)
        echo ServiceConnectionName ${{ ServiceConnectionName}}
      displayName: 'echo Pipeline Library'
    - script: |
        echo AZRMServiceConnectionName $(AZRMServiceConnectionName)
        echo DeploymentDefaultLocation $(DeploymentDefaultLocation)
      displayName: 'echo Global Variables'
    - script: |
        echo Environment ${{ parameters.Environment }}
        echo lowerEnvironment ${{ lowerEnvironment }}
      displayName: 'echo Parameters'