#name: "Variables Demo"

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

parameters:
- name : Region
  displayName: Which region to deploy to.
  type: string
  default: 'West Europe'
  values:
  - 'Germany West Central'
  - 'West Europe'
- name : Environment
  displayName: Environment to deploy.
  type: string
  default: Dev
  values:
  - Dev
  - QA
  - PRD

#- group: GlobalVariables
variables:
- template: vars.yml  # Template reference  
- group: GlobalVariables
- group: Group-1
- group: Group-2

stages:
- stage: Stage1
  displayName: "Stage 1"
  jobs:
  - job: 'echoVariables'
    strategy:
      maxParallel: 2
    steps:
    - script: |
        echo Buildnumber $(Build.BuildNumber)
      displayName: 'echo Build.BuildNumber'
    - script: |
        echo My favorite vegetable is ${{ variables.favoriteVeggie }}
        echo favoriteVeggie is $(favoriteVeggie)
        echo lowerEnvironment is $(lowerEnvironment)
        echo lowerEnvironment variable is ${{ variables.lowerEnvironment }}
      displayName: 'echo vars.yml'
    - script: |
        echo VMAdminPWD $(VMAdminPWD)
        echo AzSubscriptionID $(AzSubscriptionID)
        echo ServiceConnectionName $(ServiceConnectionName)
        echo TestVar1 $(TestVar1)
        echo TestVar2 $(TestVar2)
      displayName: 'echo Library Groups'
    - script: |
        echo Region is $(Region)
        echo Environment is $(Environment)
      displayName: 'echo parameters'
