name: "Variables Demo"

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

parameters:
- name : Region
  displayName: Which region to deploy to.
  type: string
  default: 'West Europe'
  values:
  - 'Germany West Central'
  - 'West Europe'
- name : Environment
  displayName: Environment to deploy.
  type: string
  default: Dev
  values:
  - Dev
  - QA
  - PRD

#- group: GlobalVariables
variables:
  DeploymentDefaultLocation: 'westeurope'
  AZRMServiceConnectionName: 'ARMConnection'
  lowerEnvironment: ${{ lower(parameters.Environment) }}
  ServiceConnectionName: 'ARMConnection'

stages:
- stage: Stage1
  displayName: "Stage 1"
  jobs:
  - job: Write-Output Variables
    strategy:
      maxParallel: 2
    steps:
    - script: |
        Write-Output Buildnumber $(Build.BuildNumber)
      displayName: 'Write-Output Build Number'
    - powershell: |
        Try{Write-Output AzSubscriptionID should be visible:}catch{$PSItem}
        Try{Write-Output AzSubscriptionID $(AzSubscriptionID)}catch{$PSItem}
        Try{Write-Output ServiceConnectionName Should be visible:}catch{$PSItem}
        Try{Write-Output ServiceConnectionName $(ServiceConnectionName)}catch{$PSItem}
      displayName: 'Write-Output Pipeline Library'
    - powershell: |
        Try{Write-Output AZRMServiceConnectionName $(AZRMServiceConnectionName)}catch{$PSItem}
        Try{Write-Output DeploymentDefaultLocation $(DeploymentDefaultLocation)}catch{$PSItem}
      displayName: 'Write-Output Global Variables'
    - powershell: |
        Try{Write-Output Environment ${{ parameters.Environment }}}catch{$PSItem}
        Try{Write-Output lowerEnvironment ${{ lowerEnvironment }}}catch{$PSItem}
      displayName: 'Write-Output Parameters'