name: "Variables Demo"

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

parameters:
- name : Region
  displayName: Which region to deploy to.
  type: string
  default: 'West Europe'
  values:
  - 'Germany West Central'
  - 'West Europe'
- name : Environment
  displayName: Environment to deploy.
  type: string
  default: Dev
  values:
  - Dev
  - QA
  - PRD

#- group: GlobalVariables
variables:
- template: vars.yml  # Template reference  
- group: GlobalVariables
- group: Group-1
- group: Group-2

stages:
- stage: Stage1
  displayName: "Stage 1"
  jobs:
  - job: 'echo Variables'
    strategy:
      maxParallel: 2
    steps:
    - script: |
        echo Buildnumber $(Build.BuildNumber)
        echo VMAdminPWD $(VMAdminPWD)
        echo favoriteVeggie $(variables.favoriteVeggie)
        echo AzSubscriptionID $(AzSubscriptionID)
        echo ServiceConnectionName $(ServiceConnectionName)
      displayName: 'echo Variables'